### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by SY6502** [avgoncharov/how_to#2]
It is good to give better name of project (repo) other than "how_to". Maybe "send_over_tcp" or similiar but not simply "how_to" - it is equivalent to "my_project_1" = no information.

**Comment by avgoncharov** [comment]
This repository was created by me as a repository for examples which can be useful for me in future (SimpleTcpServer / send_mail etc). "How To" - it's a good name for it, to my mind.
Thank you for your comment.

**Comment by SY6502** [comment]
If this project is for your own needs, then yes - the name must be useful from your viewpoint. I decided that you share it and for that reason was the recommendation.
